name: standard-workflow
on: 
  push:
    branches:
      - '!master'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Check commit message
      run: echo "${{ github.event.head_commit.message }}" | npx commitlint  
    - name: Run ESLint
      run: npm run eslint
    - name: Run tests
      run: npm run test
    - name: Build
      run: npm run build
