name: standard-workflow
on: [pull_request, push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check commit message
      run: echo ${{ github.event.head_commit.message }} | npx commitlint
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run eslint
    - name: Build
      run: npm run build
