name: standard-workflow
on: [pull_request, push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run eslint
    - name: Commitlint CLI
      uses: bennypowers/commitlint-gh-actions@v1.0.1
    - name: Build
      run: npm run build
