name: standard-workflow
on: [pull_request, push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check commit message
      run: |
          MSG=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "::set-env name=COMMIT_MESSAGE::${MSG}"
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run eslint
    - name: Build
      run: npm run build
